### ISSUE TITLE
dockerfile's mistake  in building arm janusgraph images for arm server

### ISSUE THREAD

**Issue by startmyway** [JanusGraph/janusgraph-docker#110]
I build a janusgraph images  for arm server , use dockerfile that provided by this path:
https://github.com/JanusGraph/janusgraph-docker/tree/master/0.5

I find a mistake in the Dockerfile.
line 33:
curl -fSL https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -o yq && \
it should be correct as this:
curl -fSL https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_arm64 -o yq && \

Because the yq is different for arm64 and amd64. Amd64 is for x86 server, and arm64 is for arm server.
At the begin, I don't find the mistake. So , I can't docker run the janusgraph images normly. The logs tell me, ' /usr/bin/yq;cannot execute-binary file...'.
So I sure the yq file is not correct. I check the dockerfile, I find the mistake in line 33.

I correct the mistake, then build the images for arm server.
It is OK.

So please check all the version Dockerfile. It may be have the same mistake for building arm server images.

**Comment by FlorianHockmann** [comment]
Thanks for the additional information on how to get a version of the image running on ARM, but ARM itself is not supported yet, see: #92.
I'm closing this as it only duplicates the main issue to get ARM support (#92).
