### ISSUE TITLE
Fails to load serializers V3

### ISSUE THREAD

**Issue by terence-bigtt** [JanusGraph/janusgraph-docker#22]
Hi 
thanks for the nice docker images ! 

I just have a minor issue, namely that the version 3 of the Gyro serializers fails to load, in the images tagged 0.3+. I didn't test 0.2

Is there a way to add the dependancy somewhere ? 
Thanks !

Config sample: 
-------
serializers:
        - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
        - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
        - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
      

Error message:
--------------
6814 [main] WARN  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Could not find configured serializer class - org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0 - it will not be available
6815 [main] WARN  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Could not find configured serializer class - org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0 - it will not be available
6816 [main] WARN  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Could not find configured serializer class - org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0 - it will not be available
6912 [main]

**Comment by FlorianHockmann** [comment]
Closed as this should be fixed in newer images. On top of that, Gryo will even be removed in future versions: https://tinkerpop.apache.org/docs/current/upgrade/#_removed_gryo_messageserializers
