### ISSUE TITLE
Trouble Configuring JanusGraph Server for ConfiguredGraphFactory

### ISSUE THREAD

**Issue by ghothan** [JanusGraph/janusgraph-docker#35]
Hello,

This is not an issue, more of a general question.  How may I launch the cassandra-es template, using

```
sudo docker-compose -f docker-compose-cql-es.yml up
```

with ConfiguredGraphFactory enabled?  I've attempted to run the commands in section 9.8.2 of the following site: https://docs.janusgraph.org/0.3.0/configuredgraphfactory.html

But I am presented with the following 

```
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
==>Configured xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxxx:8182-[79a1e7fe-b188-468b-86d2-d680a60dff9a]
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxxx:8182]-[79a1e7fe-b188-468b-86d2-d680a60dff9a] - type ':remote console' to return to local mode
gremlin> map = new HashMap<String, Object>();
gremlin> map.put("storage.backend", "cql");
==>null
gremlin> map.put("storage.hostname", "jce-cassandra");
==>null
gremlin> ConfiguredGraphFactory.createConfiguration(new MapConfiguration(map));
Please add a key named "ConfigurationManagementGraph" to the "graphs" property in your YAML file and restart the server to be able to use the functionality of the ConfigurationManagementGraph class.
Type ':help' or ':h' for help.
Display stack trace? [yN]
```

Any help would be greatly appreciated!  Thanks.

**Comment by mbrukman** [comment]
This is covered in https://docs.janusgraph.org/0.3.0/configuredgraphfactory.html#configuring-JanusGraph-server-for-configuredgraphfactory, specifically:

> To be able to use the ConfiguredGraphFactory, you must configure your server to use the ConfigurationManagementGraph APIs. To do this, you have to inject a graph variable named "ConfigurationManagementGraph" in your server’s YAML’s graphs map. For example:
> 
> ```yaml
> graphManager: org.janusgraph.graphdb.management.JanusGraphManager
> graphs: {
>   ConfigurationManagementGraph: conf/JanusGraph-configurationmanagement.properties
> }
> ```

-----

On a separate note, GitHub issues should only be used for feature requests or bug reports. Please send general questions to the mailing list or the chat channel: https://github.com/janusGraph/janusgraph/#community

**Comment by ghothan** [comment]
Misha,

Thank you for the response, I appreciate your time.  I'm attempting to use the docker-compose -f docker-compose-mount.yml up command now, with the necessary changes made to the gremlin-server.yml.  But I'm getting the following output:

admin@ip-xx-xx-xx-xxx:~/janusgraph-docker$ sudo docker-compose -f docker-compose-mount-orig.yml up
Pulling janusgraph (janusgraph/janusgraph:0.2.0)...
ERROR: manifest for janusgraph/janusgraph:0.2.0 not found: manifest unknown: manifest unknown

**Comment by mbrukman** [comment]
@ghothan — please see above re: using email or chat for support questions; we do not use GitHub issues for open-ended discussion or support.

**Comment by jerlendds** [comment]
This seems like it may be an actual bug. I have spent the last three days attempting to enable support for dynamic graphs as suggested in the documentation. I've tried a number of variations that I've seen on stackoverflow and on github issues going so far as to even clone this repo and working from that. Lately I've been mounting the `janusgraph-server.yaml` and `janusgraph.properties`  to the correct locations as read only to narrow down anything interfering with the configuration. You may find more info here: https://github.com/JanusGraph/janusgraph/issues/1322
