### ISSUE TITLE
Cannot call REST API of JanusGraph from Host (PostMan)

### ISSUE THREAD

**Issue by Tin-Nguyen** [JanusGraph/janusgraph-docker#39]
hi All,

I have up and ran the JanusGraph with Docker Compose (Cassandra + ElasticSearch) via [docker-compose-cql-es.yml](https://github.com/JanusGraph/janusgraph-docker/blob/master/docker-compose-cql-es.yml). The Gremlin server works well if I connect directly from inside the docker container via command:
```sh
docker exec -it jce-janusgraph ./bin/gremlin.sh
gremlin> :remote connect tinkerpop.server conf/remote.yaml
```

However, it doesn't work when I tried with Postman on my host machine with the request url
`POST http://localhost:8182`

Please give me the advise how to fix it, which configuration I'm missing. Thanks.

**Comment by FlorianHockmann** [comment]
Please ask questions like this one in our community channels like [the janusgraph-users Google group](https://groups.google.com/forum/#!forum/janusgraph-users) or in [our Gitter chat](https://gitter.im/janusgraph/janusgraph). We only use issues for bug reports or feature requests.

Access via HTTP is not supported by default. You have to enable it explicitly as described [in our docs](https://docs.janusgraph.org/basics/server/#janusgraph-server-as-a-http-endpoint).

**Comment by mdaliyan** [comment]
Is it possible to override `channelizer` from an env variable? If so, what is the name for that variable?
