### ISSUE TITLE
How do you set up cypher for gremlin in this dockerfile?

### ISSUE THREAD

**Issue by bionicles** [JanusGraph/janusgraph-docker#49]
https://github.com/opencypher/cypher-for-gremlin/wiki/Gremlin-implementations

I want to enable cypher queries but not sure how.

Would it be possible to please provide some guidance on how we'd integrate the cypher plugin into the janusgraph docker?

Then we'd add a whole new query language just by adding a couple lines of code. 

Thanks in advance for any help on this, 

Bion

**Comment by FlorianHockmann** [comment]
I think this is documented here for JanusGraph Server in general: https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-server-plugin#installation
and it should work basically the same for the Docker image.

I'm not sure though whether we want to include this in our own docs, considering that this doesn't seem to be that actively maintained. If we however want to document installation of this plugin somehow, then we should probably first do it for JanusGraph in general before we add docs only for the Docker image.
Please [create an issue in the main repository](https://github.com/JanusGraph/janusgraph/issues/new?assignees=&labels=&template=feature-request.md) if you think that this should be documented in the JanusGraph docs.
