### ISSUE TITLE
Unable to push images to docker hub

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph-docker#53]
Currently master builds failes with unable to deploy images to docker hub.

@mbrukman Any idea?

**Comment by mbrukman** [comment]
@farodin91 — does the build succeed, but the push fails? Can you point to a specific error log?

/cc: @FlorianHockmann as he may have ran into this and debugged it in the past.

**Comment by FlorianHockmann** [comment]
The last lines of the [build log](https://travis-ci.org/github/JanusGraph/janusgraph-docker/jobs/665007007?utm_medium=notification&utm_source=github_status) are:

> Login Succeeded
>
>invalid reference format
>
>Script failed with status 1
>
>failed to deploy

I have no idea what could cause this as `invalid reference format` seems to be very generic.

**Comment by farodin91** [comment]
In the default case the user has no right to push.

**Comment by FlorianHockmann** [comment]
I don't think that it's a permission issue as the automation user we're using on Docker Hub has the _Owner_ permission for the JanusGraph organization which contains the `JanusGraph/janusgraph` repository. I also verified that we still have the env vars set in Travis for username and password.
I can also add you to the organization on Docker Hub, @farodin91, if that helps with debugging this.

**Comment by sjudeng** [comment]
You could get that invalid reference format error if you try to push with an empty tag (e.g. `docker push "janusgraph/janusgraph:`). If `full_version` could be empty [here](https://github.com/JanusGraph/janusgraph-docker/blob/db7b8aba6ba506c10ae22861cc2aafbda203768e/push-images.sh#L31) it might explain it though it doesn't look like it would be (the logic is the same as in build-images.sh, which worked). Might put a print statement in there on it.
