### ISSUE TITLE
JanusGraph Memory Utilization with Cassandra-ES

### ISSUE THREAD

**Issue by seanjohn7944** [JanusGraph/janusgraph-docker#58]
I am running the base JG-CA-ES configuration and notice rising memory utilization (+3GB in 24 hours).  In this configuration I am making no external queries; the trio are started up and left alone.

Has anyone else experienced this issue?

**Comment by FlorianHockmann** [comment]
Closing as this is more of a usage question than a feature request or bug report and [you already asked this on janusgraph-users](https://groups.google.com/forum/#!topic/janusgraph-users/lI6dgepUjt8) which is the correct place for these kind of questions. If the discussion there comes to the conclusion that there is a bug or possible improvement in the JanusGraph Docker image, then we can still create an issue here with all the needed information to actually implement this.
