### ISSUE TITLE
Delete component in gremlin-server.yml does not work

### ISSUE THREAD

**Issue by eanton86** [JanusGraph/janusgraph-docker#78]
I'm trying to [delete graph component](https://github.com/JanusGraph/janusgraph-docker#delete-a-component) in gremlin-server.yml. The command from the example does not change anything:
```
docker run --rm -it -e gremlinserver%d.graphs.graph= docker.io/janusgraph/janusgraph:latest janusgraph show-config
....
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs:
  graph: /etc/opt/janusgraph/janusgraph.properties
scriptEngines:
....
```
 @nvizo

**Comment by nvizo** [comment]
Yes it seems this is happening with any gremlinserver configuration that has a default ENV in the [Dockerfile](https://github.com/JanusGraph/janusgraph-docker/blob/master/build/Dockerfile-openjdk8.template). I will try to resolve this soon.
