### ISSUE TITLE
Dockerfile USER breaks gremlin remote shell

### ISSUE THREAD

**Issue by lnnwvr** [JanusGraph/janusgraph-docker#82]
USER janusgraph in Dockerfile disables the possibility of using root account in kubernetes environment becuase user janusgraph has no home directory which is required by gremlin.sh remote sessions

**Comment by farodin91** [comment]
Wouldn't be the easiest solution to create a home directory?

**Comment by farodin91** [comment]
Would it be possible to provide an example? So,  i can test it out.

**Comment by lnnwvr** [comment]
If you run the container in Kubernetes you cant open a root shell into the container. So yes i can create a shared volume  mount in /home and create the folder with an initcontainer. But that is a bit to complicated. We also can not use the image anymore for running automated gremlin scripts.

To reproduce: just start a container, su to janusgraph, lauch bin/gremlin.sh and :remote connect tinkerpop.server conf/remote.yaml session

**Comment by farodin91** [comment]
You could temporary switch to the tag docker.io/janusgraph/janusgraph:0.5.3-74bd960.

**Comment by FlorianHockmann** [comment]
@farodin91 Isn't this fixed now that #84 is merged?

**Comment by farodin91** [comment]
It should be fixed by #84.

**Comment by FlorianHockmann** [comment]
Then I'll close this. @lnnwvr: Please re-open / create a new issue if this is still a problem with the most recent images.
