### ISSUE TITLE
Publish images to Docker Hub

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph-docker#9]
What are the steps to publish JanusGraph Docker images to Docker Hub? Related issue is https://github.com/JanusGraph/janusgraph/issues/337. @amcp Are you still holding the janusgraph org in Docker Hub?

- [x] JanusGraph organization account on Docker Hub
- [x] JanusGraph Docker Hub credential (password) as encrypted variable in [.travis.yml](https://github.com/JanusGraph/janusgraph-docker/blob/master/.travis.yml)
- [ ] Image(s) pushed to Docker Hub in [.travis.yml](https://github.com/JanusGraph/janusgraph-docker/blob/master/.travis.yml) (see [push-images.sh](https://github.com/JanusGraph/janusgraph-docker/blob/master/push-images.sh) script).

**Comment by FlorianHockmann** [comment]
@amcp It would be really great if we could move forward here and finally publish our image.

**Comment by FlorianHockmann** [comment]
Quick update on this: @amcp added a few TSC members as owners to the JanusGraph organization on Docker Hub and he also created an account that we can use for automation.
I'll create a PR shortly to enable continuous deployment via Travis.
